nginx role improvement

diff --git a/roles/nginx-1.8.1-ubuntu-14.04-from-source/templates/nginx.j2 b/roles/nginx-1.8.1-ubuntu-14.04-from-source/templates/nginx.j2
--- a/roles/nginx-1.8.1-ubuntu-14.04-from-source/templates/nginx.j2
+++ b/roles/nginx-1.8.1-ubuntu-14.04-from-source/templates/nginx.j2
@@ -1,210 +1,408 @@
-#!/bin/sh
-
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:	  nginx
-# Required-Start:    $local_fs $remote_fs $network $syslog $named
-# Required-Stop:     $local_fs $remote_fs $network $syslog $named
+# Provides:          nginx
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts the nginx web server
-# Description:       starts nginx using start-stop-daemon
+# Short-Description: nginx init.d dash script for Ubuntu or other *nix.
+# Description:       nginx init.d dash script for Ubuntu or other *nix.
 ### END INIT INFO
+#------------------------------------------------------------------------------
+# nginx - this Debian Almquist shell (dash) script, starts and stops the nginx
+#         daemon for Ubuntu and other *nix releases.
+#
+# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
+#               proxy and IMAP/POP3 proxy server.  This \
+#               script will manage the initiation of the \
+#               server and it's process state.
+#
+# processname: nginx
+# config:      /usr/local/nginx/conf/nginx.conf
+# pidfile:     /usr/local/nginx/logs/nginx.pid
+# Provides:    nginx
+#
+# Author:  Jason Giedymin
+#          <jason.giedymin AT gmail.com>.
+#
+# Version: 3.9.0 12-MAY-2015 jason.giedymin AT gmail.com
+# Notes: nginx init.d dash script for Ubuntu.
+# Tested with: Ubuntu 14.10, nginx-1.7.9
+#
+# This script's project home is:
+#   http://github.com/JasonGiedymin/nginx-init-ubuntu
+#
+#------------------------------------------------------------------------------
+#                               MIT X11 License
+#------------------------------------------------------------------------------
+#
+# Copyright (c) 2008-2013 Jason Giedymin, http://jasongiedymin.com
+#
+# Permission is hereby granted, free of charge, to any person obtaining
+# a copy of this software and associated documentation files (the
+# "Software"), to deal in the Software without restriction, including
+# without limitation the rights to use, copy, modify, merge, publish,
+# distribute, sublicense, and/or sell copies of the Software, and to
+# permit persons to whom the Software is furnished to do so, subject to
+# the following conditions:
+#
+# The above copyright notice and this permission notice shall be
+# included in all copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
+# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
+# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
+# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
+# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+#------------------------------------------------------------------------------
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/nginx
-NAME=nginx
-DESC=nginx
+#------------------------------------------------------------------------------
+#                               Functions
+#------------------------------------------------------------------------------
+LSB_FUNC=/lib/lsb/init-functions
 
+# Test that init functions exists
+test -r $LSB_FUNC || {
+    echo "$0: Cannot find $LSB_FUNC! Script exiting." 1>&2
+    exit 5
+}
+
+. $LSB_FUNC
+
+#------------------------------------------------------------------------------
+#                               Consts
+#------------------------------------------------------------------------------
 # Include nginx defaults if available
-if [ -r /etc/default/nginx ]; then
-	. /etc/default/nginx
+if [ -f /etc/default/nginx ]; then
+    . /etc/default/nginx
 fi
 
-test -x $DAEMON || exit 0
+# Minimize path
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
-. /lib/init/vars.sh
-. /lib/lsb/init-functions
+PS=${PS:-"nginx"}                             # process name
+DESCRIPTION=${DESCRIPTION:-"Nginx Server..."} # process description
+NGINXPATH=${NGINXPATH:-/usr/local/nginx}      # root path where installed
+DAEMON=/usr/sbin/nginx       # path to daemon binary
+NGINX_CONF_FILE=${NGINX_CONF_FILE:-$NGINXPATH/conf/nginx.conf} # config file path
 
-# Try to extract nginx pidfile
-PID=$(cat /usr/local/nginx/conf/nginx.conf | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
-if [ -z "$PID" ]
-then
-	PID=/run/nginx.pid
-fi
+PIDNAME=${PIDNAME:-"nginx"}                   # lets you do $PS-slave
+PIDFILE=${PIDFILE:-$PIDNAME.pid}              # pid file
+PIDSPATH=${PIDSPATH:-$NGINXPATH/logs}         # default pid location, you should change it
+RUNAS=${RUNAS:-root}                          # user to run as
 
-# Check if the ULIMIT is set in /etc/default/nginx
-if [ -n "$ULIMIT" ]; then
-	# Set the ulimits
-	ulimit $ULIMIT
-fi
+SCRIPT_OK=0           # ala error codes
+SCRIPT_ERROR=1        # ala error codes
+TRUE=1                # boolean
+FALSE=0               # boolean
 
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
-		$DAEMON_OPTS 2>/dev/null \
-		|| return 2
+#------------------------------------------------------------------------------
+#                               Simple Tests
+#------------------------------------------------------------------------------
+
+# Test if nginx is a file and executable
+test -x $DAEMON || {
+    echo "$0: You don't have permissions to execute nginx." 1>&2
+    exit 4
 }
 
-test_nginx_config() {
-	$DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+# You can also set your conditions like so:
+# set exit condition
+# set -e
+
+#------------------------------------------------------------------------------
+#                               Functions
+#------------------------------------------------------------------------------
+
+setFilePerms(){
+    if [ -f $PIDSPATH/$PIDFILE ]; then
+        chmod 400 $PIDSPATH/$PIDFILE
+    fi
 }
 
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --name $NAME
-	RETVAL="$?"
-
-	sleep 1
-	return "$RETVAL"
+configtest() {
+    $DAEMON -t -c $NGINX_CONF_FILE
 }
 
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
-	return 0
+getPSCount() {
+    return `pgrep -f $PS | wc -l`
 }
 
-#
-# Rotate log files
-#
-do_rotate() {
-	start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
-	return 0
+isRunning() {
+    if [ $1 ]; then
+        pidof_daemon $1
+        PID=$?
+
+        if [ $PID -gt 0 ]; then
+            return 1
+        else
+            return 0
+        fi
+    else
+        pidof_daemon
+        PID=$?
+
+        if [ $PID -gt 0 ]; then
+            return 1
+        else
+            return 0
+        fi
+    fi
 }
 
-#
-# Online upgrade nginx executable
-#
-# "Upgrading Executable on the Fly"
-# http://nginx.org/en/docs/control.html
-#
-do_upgrade() {
-	# Return
-	#   0 if nginx has been successfully upgraded
-	#   1 if nginx is not running
-	#   2 if the pid files were not created on time
-	#   3 if the old master could not be killed
-	if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
-		# Wait for both old and new master to write their pid file
-		while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
-			cnt=`expr $cnt + 1`
-			if [ $cnt -gt 10 ]; then
-				return 2
-			fi
-			sleep 1
-		done
-		# Everything is ready, gracefully stop the old master
-		if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
-			return 0
-		else
-			return 3
-		fi
-	else
-		return 1
-	fi
+#courtesy of php-fpm
+wait_for_pid () {
+    try=0
+
+    while test $try -lt 35 ; do
+        case "$1" in
+            'created')
+            if [ -f "$2" ]; then
+                try=''
+                break
+            fi
+            ;;
+
+            'removed')
+            if [ ! -f "$2" ]; then
+                try=''
+                break
+            fi
+            ;;
+        esac
+
+        try=`expr $try + 1`
+        sleep 1
+    done
 }
 
+status(){
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
+        log_warning_msg "$DESCRIPTION found running with processes:  `pidof $PS`"
+        rc=0
+    else
+        log_warning_msg "$DESCRIPTION is NOT running."
+        rc=3
+    fi
+
+    return
+}
+
+removePIDFile(){
+    if [ $1 ]; then
+        if [ -f $1 ]; then
+            rm -f $1
+        fi
+    else
+        #Do default removal
+        if [ -f $PIDSPATH/$PIDFILE ]; then
+            rm -f $PIDSPATH/$PIDFILE
+        fi
+    fi
+}
+
+start() {
+    log_daemon_msg "Starting $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
+        log_end_msg $SCRIPT_ERROR
+        rc=0
+    else
+        start-stop-daemon --start --quiet --chuid \
+        $RUNAS --pidfile $PIDSPATH/$PIDFILE --exec $DAEMON \
+        -- -c $NGINX_CONF_FILE
+        status=$?
+        setFilePerms
+
+        if [ "${status}" -eq 0 ]; then
+            log_end_msg $SCRIPT_OK
+            rc=0
+        else
+            log_end_msg $SCRIPT_ERROR
+            rc=7
+        fi
+    fi
+
+    return
+}
+
+stop() {
+    log_daemon_msg "Stopping $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
+        start-stop-daemon --stop --quiet --pidfile $PIDSPATH/$PIDFILE
+
+        wait_for_pid 'removed' $PIDSPATH/$PIDFILE
+
+        if [ -n "$try" ]; then
+            log_end_msg $SCRIPT_ERROR
+            rc=0 # lsb states 1, but under status it is 2 (which is more prescriptive). Deferring to standard.
+        else
+            removePIDFile
+            log_end_msg $SCRIPT_OK
+            rc=0
+        fi
+    else
+        log_end_msg $SCRIPT_ERROR
+        rc=7
+    fi
+
+    return
+}
+
+reload() {
+    configtest || return $?
+
+    log_daemon_msg "Reloading (via HUP) $DESCRIPTION"
+
+    isRunning
+
+    if [ $? -eq $TRUE ]; then
+        kill -HUP `cat $PIDSPATH/$PIDFILE`
+        log_end_msg $SCRIPT_OK
+        rc=0
+    else
+        log_end_msg $SCRIPT_ERROR
+        rc=7
+    fi
+
+    return
+}
+
+quietupgrade() {
+    log_daemon_msg "Peforming Quiet Upgrade $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
+        kill -USR2 `cat $PIDSPATH/$PIDFILE`
+        kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
+
+        isRunning
+        isAlive=$?
+
+        if [ "${isAlive}" -eq $TRUE ]; then
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+            removePIDFile $PIDSPATH/$PIDFILE.oldbin
+
+            log_end_msg $SCRIPT_OK
+            rc=0
+        else
+            log_end_msg $SCRIPT_ERROR
+
+            log_daemon_msg "ERROR! Reverting back to original $DESCRIPTION"
+
+            kill -HUP `cat $PIDSPATH/$PIDFILE`
+            kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+            removePIDFile $PIDSPATH/$PIDFILE.oldbin
+
+            log_end_msg $SCRIPT_OK
+            rc=0
+        fi
+    else
+        log_end_msg $SCRIPT_ERROR
+        rc=7
+    fi
+
+    return
+}
+
+terminate() {
+    log_daemon_msg "Force terminating (via KILL) $DESCRIPTION"
+
+    PIDS=`pidof $PS` || true
+
+    [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
+
+    for i in $PIDS; do
+        if [ "$i" = "$PIDS2" ]; then
+            kill $i
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE
+            removePIDFile
+        fi
+    done
+
+    log_end_msg $SCRIPT_OK
+    rc=0
+}
+
+destroy() {
+    log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
+    killall $PS -q >> /dev/null 2>&1
+    log_end_msg $SCRIPT_OK
+    rc=0
+}
+
+pidof_daemon() {
+    PIDS=`pidof $PS` || true
+
+    [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
+
+    for i in $PIDS; do
+        if [ "$i" = "$PIDS2" ]; then
+            return 1
+        fi
+    done
+
+    return 0
+}
+
+action="$1"
 case "$1" in
-	start)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-		do_start
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
-	stop)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
-	restart)
-		log_daemon_msg "Restarting $DESC" "$NAME"
-
-		# Check configuration before stopping nginx
-		if ! test_nginx_config; then
-			log_end_msg 1 # Configuration error
-			exit 0
-		fi
-
-		do_stop
-		case "$?" in
-			0|1)
-				do_start
-				case "$?" in
-					0) log_end_msg 0 ;;
-					1) log_end_msg 1 ;; # Old process is still running
-					*) log_end_msg 1 ;; # Failed to start
-				esac
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
-		esac
-		;;
-	reload|force-reload)
-		log_daemon_msg "Reloading $DESC configuration" "$NAME"
-
-		# Check configuration before reload nginx
-		#
-		# This is not entirely correct since the on-disk nginx binary
-		# may differ from the in-memory one, but that's not common.
-		# We prefer to check the configuration and return an error
-		# to the administrator.
-		if ! test_nginx_config; then
-			log_end_msg 1 # Configuration error
-			exit 0
-		fi
-
-		do_reload
-		log_end_msg $?
-		;;
-	configtest|testconfig)
-		log_daemon_msg "Testing $DESC configuration"
-		test_nginx_config
-		log_end_msg $?
-		;;
-	status)
-		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-		;;
-	upgrade)
-		log_daemon_msg "Upgrading binary" "$NAME"
-		do_upgrade
-		log_end_msg 0
-		;;
-	rotate)
-		log_daemon_msg "Re-opening $DESC log files" "$NAME"
-		do_rotate
-		log_end_msg $?
-		;;
-	*)
-		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest|rotate|upgrade}" >&2
-		exit 3
-		;;
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart|force-reload)
+        stop
+        # if [ $rc -ne 0 ]; then
+        #     script_exit
+        # fi
+        sleep 1
+        start
+        ;;
+    reload)
+        $1
+        ;;
+    status)
+        status
+        ;;
+    configtest)
+        $1
+        ;;
+    quietupgrade)
+        $1
+        ;;
+    terminate)
+        $1
+        ;;
+    destroy)
+        $1
+        ;;
+    *)
+        FULLPATH=/etc/init.d/$PS
+        echo "Usage: $FULLPATH {start|stop|restart|force-reload|reload|status|configtest|quietupgrade|terminate|destroy}"
+        echo "       The 'destroy' command should only be used as a last resort."
+        exit 3
+        ;;
 esac
 
-:
-
+exit $rc
